shared: &shared
  docker:
    - image: docker:stable-git
  environment:
    UBUNTU_VERSION: "18.04"
  steps:
    - checkout
    - setup_remote_docker:
        version: 17.05.0-ce
    - run:
        name: Build image
        command: |
          ./build-image.sh $CIRCLE_JOB
        environment:
          IMAGE_USER: lmmsci
          IMAGE_PREFIX: ""
          DOCKER_ARGS: "--build-arg UBUNTU_VERSION=$UBUNTU_VERSION"
version: 2
jobs:
  base:18.04:
    <<: *shared
  linux:18.04:
    <<: *shared
  linux.mingw:18.04:
    <<: *shared
  linux.mingw32:18.04:
    <<: *shared
  linux.mingw64:18.04:
    <<: *shared
workflows:
  version: 2
  build_images:
    jobs:
      - base:18.04
      - linux:18.04:
          requires:
           - base:18.04
      - linux.gcc:18.04:
          requires:
           - linux:18.04
      - linux.mingw:18.04:
          requires:
           - base:18.04
      - linux.mingw32:18.04:
          requires:
           - linux.mingw:18.04
      - linux.mingw64:18.04:
          requires:
           - linux.mingw:18.04
