shared: &shared
  docker:
    - image: docker:stable-git
  environment:
    UBUNTU_VERSION: "18.04"
  steps:
    - checkout
    - setup_remote_docker:
        version: 17.05.0-ce
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Load archived Docker image
        command: if [ -f /tmp/workspace/image.tar.gz ]; then docker load -i /tmp/workspace/image.tar.gz; fi
    - run:
        name: Build image
        command: |
          ./build-image.sh $CIRCLE_JOB
        environment:
          IMAGE_USER: lmmsci
          IMAGE_PREFIX: ""
    - persist_to_workspace:
        root: .
        paths:
          - ./image.tar.gz

focal: &focal
  <<: *shared
  environment:
    UBUNTU_VERSION: "20.04"

version: 2
jobs:
  base:18.04:
    <<: *shared
  base:20.04:
    <<: *focal
  linux:18.04:
    <<: *shared
  linux.gcc:18.04:
    <<: *shared
  linux.mingw:20.04:
    <<: *focal
  linux.mingw32:20.04:
    <<: *focal
  linux.mingw64:20.04:
    <<: *focal
workflows:
  version: 2
  build_images:
    jobs:
      - base:18.04
      - base:20.04
      - linux:18.04:
          requires:
           - base:18.04
      - linux.gcc:18.04:
          requires:
           - linux:18.04
      - linux.mingw:20.04:
          requires:
           - base:20.04
      - linux.mingw32:20.04:
          requires:
           - linux.mingw:20.04
      - linux.mingw64:20.04:
          requires:
           - linux.mingw:20.04
